// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Blog.IntegrationTests;
//
//    var users = Users.FromJson(jsonString);

namespace Blog.IntegrationTests
{
    using Newtonsoft.Json;

    public static class Serialize
    {
        public static string ToJson(this Users self) => JsonConvert.SerializeObject(self, Converter.Settings);

        public static string ToJson(this Password self) => JsonConvert.SerializeObject(self, Converter.Settings);

        public static string ToJson(this Article self) => JsonConvert.SerializeObject(self, Converter.Settings);

    }
}
