// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Blog.IntegrationTests;
//
//    var users = Users.FromJson(jsonString);

namespace Blog.IntegrationTests
{
    using Newtonsoft.Json;

    public partial class Users
    {
        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("fullname")]
        public string FullName { get; set; }

        [JsonProperty("password")]
        public string Password { get; set; }

        [JsonProperty("confirmPassword")]
        public string ConfirmPassword { get; set; }

        public static Users FromJson(string json) => JsonConvert.DeserializeObject<Users>(json, Converter.Settings);


    }
}
